[[deployment.targets]]
name = "github"
URL = "https://github.com/desert98/desert98.github.io.git"
branch = "main"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
cacheControl = "no-cache, no-store, must-revalidate"
